version: '3.8'

services:
  frontend:
    image: jhonmayta/frontend_example_docker:latest
    container_name: frontend_container
    ports:
      - "80:80" 
    restart: always
    environment:
      - VITE_API_URL=http://137.131.140.228:3000  
    networks:
      - app_network

  backend:
    image: jhonmayta/backend_example_docker:latest
    container_name: backend_container
    ports:
      - "3000:3000"  
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge  
